### ISSUE TITLE
Add Pythagoras Tree

### ISSUE THREAD

**Issue by trebeljahr** [trebeljahr/fractal-garden#16]
## Description
Add an implementation of the Pythagoras Tree. Show connections to Lévy Curve and Fractal Tree/Canopy. 
Angle should be variable -> Symmetry should be variable.

## Inspiration
[Wikipedia - Pythagoras Tree](https://en.wikipedia.org/wiki/Pythagoras_tree_(fractal))
[Larry Riddle - Pythagorean Tree](https://larryriddle.agnesscott.org/ifs/pythagorean/pythTree.htm)

## Type
Recursive / Canvas

## Difficulties
None really.

**Comment by npx** [comment]
Check out the MR @trebeljahr :)

And I'd like to extend my thanks for this great project, it gave me the fun challenge I was looking for! It is well setup, maintained and documented, so it was easy for me to get into it! Cheers
