### ISSUE TITLE
Barnsley-Fern broken on mobile

### ISSUE THREAD

**Issue by trebeljahr** [trebeljahr/fractal-garden#17]
![image](https://user-images.githubusercontent.com/25333032/193275075-a8d58901-34c6-483e-a827-61ee780fc5ee.png)

When on Mobile the Barnsley Fern does not show correctly.

**Comment by npx** [comment]
Hey, I implemented a solution for this, however, this problem is not trivial, as we cannot (easily) determine the actual size of the final fractal, thus scaling it to the canvas is tricky. Especially, if we look at fractals growing horizontally (like the tree).
This btw applies to all your growing fractals, and ideally a general solution for all of those is applied.

What do you consider feasible for an implementation.

**Comment by trebeljahr** [comment]
one thing I noticed while testing, some of the ferns are a little small now on mobile: 

![image](https://user-images.githubusercontent.com/25333032/194283682-3f534c02-093c-494a-ab0c-a65bc559bf2a.png)
![image](https://user-images.githubusercontent.com/25333032/194283791-bead6989-29f8-4084-831f-d50ca81c62be.png)

It would be cool if they could stretch further to the left and right :) 

When I tried to look for a generic approach to calculate the width/height of those Ferns, I didn't come up with anything good either. 

There is [this part of Wikipedia with the Algorithms](https://en.wikipedia.org/wiki/Barnsley_fern#:~:text=let%20px%20%3D%20map(x%2C%20%2D2.1820%2C%202.6558%2C%200%2C%20width)%3B), but they also just draw points and map them with some magic numbers to X/Y coordinates... 

But like I said, fiddling with magic numbers and adding them to the transformation rules would be 100% fine with me :)

**Comment by trebeljahr** [comment]
an idea of how to find those points is by keeping track of the points drawn in an array, then reducing it to find the min/max for the x/y values, and then using those in the map/remap function, as you see in Wikipedia. This way you can find out the range of the points you get from the transformations for the specific fern.

For the Barnsley Fern those would be: 
−2.1820 < x < 2.6558
 0 ≤ y < 9.9983
 
and with the approach above you could find them for the other variants and then map accordingly :) 
 
and the ratio between highX - lowX and highY - lowY gives you an aspect ratio you could use for figuring out whether something is "width" or "height" scaling as well :blush: so you don't have to hardcode it :+1:

**Comment by trebeljahr** [comment]
this would then be a semi-general solution - it would still involve finding and then hardcoding the upper/lower x/y bounds for each of the ferns, but then the centering would be done for all, in the same way, using that data :+1:

**Comment by npx** [comment]
Thanks for looking into it! 
Yeah I had a similar train of thought when looking at the implementation haha

However, even when determining the values and adding some fractal specific settings, fractals growing extremely in width (like the tree) will become rather small on a phone screen in portrait mode.

I'll see what I can do!

**Comment by trebeljahr** [comment]
thank you so much :) let me know how it goes, or if you need anything from me :+1:

**Comment by npx** [comment]
Hey @trebeljahr,

I worked over the implementation and the result is "relatively" decent. You will find that now all trees will fit into the viewport correctly.

However, upon closer inspection of your implementation (which I assume was heavily inspired by the JS example in the wiki you linked hehe) I found that you implemented a kind of custom scaling - rather a distortion - which was applied to all ferns.

I have removed this for this iteration of the implementation, as it is not really part of the algorithm. Futhermore, I removed the `scalingFactor` for now. I experimented with scaling the width and height with custom values, but it didnt really look to neat tbh.

Please check out the current behaviour and implementation and if this is fine, I would urge you to merge it as is for now, and open a new ticket to add a custom distortion function per fern!

Let me know what you think!

**Comment by trebeljahr** [comment]
cool, just saw your comment now, checking it out :) at a first glance the work looks amazing thank you so much for taking the time :+1:

**Comment by trebeljahr** [comment]
I think the padding is a bit much as it is right now on small screens – 320 - 200, does not leave much place for the ferns ^^ Let's change that to a percentage-based value of say 80% or 85% or 90% of the available width/height and then it should be perfect I think and we can merge this :) 

the thing you found with the distortion is super interesting, thanks for figuring it out! 

The Barnsley Fern looks much thinner now ^^ To me it's interesting since the version on the Wikipedia page for the p5.js is different from the native canvas one and my guess would be that they give different results as well (the custom distorting one looks broader probably). 

Even if you punch that into google images you get different versions :man_shrugging: some really broad, others very narrow... 

![image](https://user-images.githubusercontent.com/25333032/195553364-379c642d-d7a2-43e0-98de-62aaf1e9216b.png)

**Comment by npx** [comment]
I personally think the fern looks a bit more elegant without he distortion but thats just my personal opinion haha
I will quickly adjust to a percentage based padding and send you the update!

**Comment by npx** [comment]
When switching to percentage padding, I've noticed my remapping and positioning being off. After a bit more napkin math, i should now be remapped and positioned properly!

Check it out >:3

**Comment by trebeljahr** [comment]
just checked it out! now it's perfect <3 thank you so much :) I'll merge this then :+1:
