### ISSUE TITLE
Fractal-Tree broken on mobile

### ISSUE THREAD

**Issue by trebeljahr** [trebeljahr/fractal-garden#18]
![image](https://user-images.githubusercontent.com/25333032/193275403-f50849ed-5659-4c73-a39d-2f82fa27ee6c.png)

The Fractal-Tree / Fractal-Canopy doesn't show nicely on mobile. Needs some calculations to figure out the maximum Root Length based on the current settings, to stay within the bounds of the screen.

**Comment by npx** [comment]
Hey I didnt check out the code yet, but isnt that similar to what I have worked on?

I was wondering, if you would like me to outsource and refactor my work with proper interfaces so the scaling logic can be re-used. If so, what about you create another issue for the outsourcing and assign it to me, ill take care of it.

Afterwards we can go through the fractals one by one to refactor to reuse that logic.
What do you think?

**Comment by trebeljahr** [comment]
Sry I didn't see that. Not the most on top of things sometimes, should really enable notifications for this repo haha :sweat_smile: 

I like the idea, the outsourcing is already done, so now it's just a question of using that same logic to close this issue right? 

There is one problem I see you could run into with this approach, namely the different fractals will have different algorithms and hence you might need to figure out how to adapt the Barnsley Fern approach to new types of fractals that don't have a mapping to the idea of "furthest point left,right,up,down". 

Especially L-Systems could be a bit of a problem since they are just long strings executed as draw instructions one by one and the scaling happens in between iterations with some magic numbers. 

Let me know how it goes/if you need help :+1:

**Comment by npx** [comment]
Well I guess we need to find different ways to determine the sizes depending on the fractals. I could not really abstract for the canopy :c
But once there are multiple following certain scaling logics, it would make sense to refactor. Like determine scaling directing depending on a growth function or something. 

// I will just hit you with the @trebeljahr this time haha check out the PR at your leisure :)
